### ISSUE TITLE
Holy Bruh 💀 💯 💯 👍 🥇 

### ISSUE THREAD

**Issue by ameydhamgunde** [ericmshen/262-chat-app-plus#1]
first lemme hop out the muh f***in porshe
ion want her if that a** dont sit like a horse
i be ballin on these ____ got me feelin like sports
dash got so much wood i could build me a fort

ain't too many things I ain't done yet
I'm the king of this sh** crowned by the toilet
im just barely gettin started you already upset
got a tiger as a pet i just took him to the vet

**Comment by ericmshen** [comment]
Ack
